### ISSUE TITLE
On Backpack Wallet : Why Joy NFTs Collection not showing up??

### ISSUE THREAD

**Issue by dbwebapp** [daoplays/LetsCook#184]
this is a screenshot of my Backpack Wallet, and my Joy NFTs not showing up on Collectibles Section : 
<img width="382" alt="Screenshot 205" src="https://github.com/user-attachments/assets/8889d434-ca0b-4d5c-8c27-dd1e9ee642dd">

**Comment by Chloebarbers** [comment]
hope your issue is resolved by now. If not, I apologize for the delay. It seems you're facing a transcript error, likely due to a system glitch. Please reach out to the support team for assistance with the recovery process.I'll have to refer you to the official support live chat with the ticket ID BAC07638
Please see the link below to our dedicated support line:
[Backpack wallet Network DApps Support Ticket Requests.]https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@artontray

**Comment by daoplays** [comment]
unfortunately this is a backpack support issue, apparently it is coming "soon"
